gp650_turtlesim_teleop:
  ros__parameters:
    axis_linear: 1
    axis_angular: 0
    scale_linear: 2.0
    scale_angular: 2.0
    deadzone: 0.1
    expo: 0.25
    enable_button: 0     # A=0, B=1, X=2, Y=3 (แล้วแต่จอย)
    invert_linear: false
    invert_angular: false

