use_map_topic: true
odom_model_type: omni
base_frame_id: base_footprint
odom_frame_id: odom
global_frame_id: map

update_min_d: 0.2
update_min_a: 0.2
resample_interval: 1

laser_max_range: 12.0
laser_z_hit: 0.95
laser_sigma_hit: 0.2
laser_z_rand: 0.05

odom_alpha1: 0.1
odom_alpha2: 0.1
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.1

min_particles: 100
max_particles: 300
