obstacle_range: 2.0
raytrace_range: 3.0
footprint: [[-0.33, -0.23], [-0.33, 0.24], [0.33, 0.24], [0.33, -0.23]]

inflation_radius: 0.1
footprint_padding: -0.02

obstacle_layer:
  observation_sources: laser
  laser:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
