DWAPlannerROS:
  max_vel_x: 0.20
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  acc_lim_x: 0.3
  acc_lim_theta: 1.0

  sim_time: 1.5
  vx_samples: 6
  vtheta_samples: 20

  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.15

  path_distance_bias: 24.0
  goal_distance_bias: 18.0
  occdist_scale: 0.02
