global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 3.0
  publish_frequency: 1.0
  static_map: true
  rolling_window: true
  transform_tolerance: 0.5
  width: 10.0
  height: 10.0
  resolution: 0.05
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  GlobalPlanner:
  allow_unknown: true
  use_quadratic: true
  orientation_mode: 1 
  use_grid_path: false
