local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 3.0
  publish_frequency: 1.0
  transform_tolerance: 0.5
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.01
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    obstacle_layer:
    footprint_clearing_enabled: true 
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: laser
      data_type: LaserScan
      topic: /scan
      marking: false
      clearing: true
      observation_persistence: 0.5               # (ช่วยให้ obstacle ไม่หายเร็วเกิน)
      min_obstacle_height: 0.3                  # (ตัดสิ่งที่ต่ำเกินไป เช่น ขอบหุ่น)
      max_obstacle_height: 1.0                   # (ตัดของสูงเกิน เช่น ประตู)

  inflation_layer:
    inflation_radius: 0.1
