controller_frequency: 12.0       # ตั้งให้ใกล้กับความถี่ /odom จริง (เริ่ม 8.0; ถ้าเพิ่มได้ค่อย 10–15)
planner_frequency: 1.0

base_global_planner: "navfn/NavfnROS"
base_local_planner:  "dwa_local_planner/DWAPlannerROS"

planner_patience:    3.0
controller_patience: 3.0
oscillation_timeout: 10.0
oscillation_distance: 0.20

recovery_behavior_enabled: true
clearing_rotation_allowed: true
shutdown_costmaps: false
